export class Business {
    constructor( 
        public id: any,
        public userId?: string,
        public rowid?: string,
        public directory?: string,
        public gravatar?: any,
        public officeName?: string,
        public firstName?: string,
        public middleName?: string,
        public lastName?: string,
        public otherNames?: string,
        public dateOfBirth?: any,
        public idType?: string,
        public idNo?: string,
        public idPicture?: any,
        public email?: string,
        public mobile?: any,
        public gender?: string,
        public street?: string,
        public city?: string,
        public state?: string,
        public country?: string,
        public maritalStatus?: string,
        public homeTown?: string,      
        public position?: string,
        public latitude?: any,
        public longitude?: any,
        public group?: string,
        public findMeId?: any,
        public location?: any,
        public websiteUrl?: string,
        public fileUpload?: any,
        public landSize?: any,
        public otherInfo?: any,
        public timeDate?: any,
        public dob?:any ) {}
}

